<?php
$answers = array(
    'selec_proyec_transv', 
    'num_est_trans',
    'num_est_pri', 
    'num_est_secun', 
    'num_est_media', 
    'inter_doc', 
    'nac_doc', 
    'dep_doc', 
    'local_doc', 
    'insti_doc', 
    'inter_doc_norm', 
    'nac_doc_norm', 
    'dep_doc_norm', 
    'local_doc_norm', 
    'insti_doc_norm', 
    'num_anos_implem', 
    'si_pei', 
    'Tem_curr_proy', 
    'Prob_curr_proy', 
    'activ_curr_proy', 
    'otros', 
    'si_mes_trab', 
    'si_prob', 
    'fuert_prob', 
    'otro_prob', 
    'si_sol_prob', 
    'fuert_art_areas', 
    'num_revis_proy', 
    'anos_rev_proyec', 
    'fec_act_proyecto', 
    'exist_niv_proy', 
    'exist_niv_proy_1', 
    'si_pmi', 
    'si_proy_vin', 
    'num_est_vin_23', 
    'si_vin_conv_esc', 
    'nomb_lid_proy', 
    'area_form_proy', 
    'niv_cicl_desp', 
    'num_anos_vin_proy', 
    'cuent_for_proyec', 
    'si_cert_form_cap', 
    'nom_curs_form_capac', 
    'si_fue_cert', 
    'si_fue_cert_num_anos', 
    'Num_contacts', 
    'secret_anos_art', 
    'centros_anos_art_sup', 
    'sena_anos_art', 
    'int_nac_dep_art', 
    'corp_jud_leg', 
    'sec_jud_leg', 
    'dep_jud_leg', 
    'de_cont_dif_edu', 
    'cent_jud_leg', 
    'ong_depto', 
    'org_priv_depto', 
    'org_com_depto', 
    'otras_depto', 
    'si_fuer_edu_art_int', 
    'si_fuer_edu_gub_int', 
    'si_fuer_edu_art_no_int', 
    'si_fuer_no_gub', 
    'inst_nom_apoy_ext', 
    'num_anos_apoy', 
    'fin_tip_apoy', 
    'log_tip_apoy', 
    'tecn_tip_apoy', 
    'tec_peda_tip_apoy', 
    'ases_tip_apoy', 
    'acomp_tip_apoy', 
    'sin_tip_apoy', 
    'fin_nec_proy', 
    'log_nec_proy', 
    'tec_nec_proy', 
    'for_doc_nec_proy', 
    'tecn_pedag_nec_proy', 
    'ases_direc_doc_nec_proy', 
    'acomp_nec_proy', 
    'no_se_req_nec_proy', 
    'log_ano_ult', 
    'tecn_ano_ult', 
    'ases_ano_ult', 
    'fin_ano_ult', 
    'form_doc_ano_ult', 
    'tec_pedag_ano_ult', 
    'otro_ano_ult', 
    'no_requie_eficaz', 
    'Fue_oport', 
    // 'id_cole', 
    // 'estado_proyec_pedag_transv', 
    // 'fecha_proyec_pedag_transv', 
    // 'id_usu'
);






$fieldTypesNewAnswers = array(
    'selec_proyec_transv' => 'char',
    'num_est_trans' => 'int',
    'num_est_pri' => 'int',
    'num_est_secun' => 'int',
    'num_est_media' => 'int',
    'inter_doc' => 'textarea',
    'nac_doc' => 'textarea',
    'dep_doc' => 'textarea',
    'local_doc' => 'textarea',
    'insti_doc' => 'textarea',
    'inter_doc_norm' => 'textarea',
    'nac_doc_norm' => 'textarea',
    'dep_doc_norm' => 'textarea',
    'local_doc_norm' => 'textarea',
    'insti_doc_norm' => 'textarea',
    'num_anos_implem' => 'int',

    'si_pei' => 'char',
    'Tem_curr_proy' => 'textarea',
    'Prob_curr_proy' => 'textarea',
    'activ_curr_proy' => 'textarea',
    'otros' => 'textarea',
    'si_mes_trab' => 'char',
    'si_prob' => 'char',
    'fuert_prob' => 'char',
    'otro_prob' => 'textarea',
    'si_sol_prob' => 'char',
    'fuert_art_areas' => 'char',
    'num_revis_proy' => 'int',
    'anos_rev_proyec' => 'int',
    'fec_act_proyecto' => 'textarea',
    'exist_niv_proy' => 'textarea',
    'exist_niv_proy_1' => 'char',
    'si_pmi' => 'char',
    'si_proy_vin' => 'char',
    'num_est_vin_23' => 'int',
    'si_vin_conv_esc' => 'char',
    'nomb_lid_proy' => 'textarea',
    'area_form_proy' => 'textarea',
    'niv_cicl_desp' => 'char',
    'num_anos_vin_proy' => 'int',
    'cuent_for_proyec' => 'textarea',
    'si_fue_cert_num_anos' => 'textarea',
    'secret_anos_art' => 'textarea',
    'sena_anos_art' => 'textarea',
    'centros_anos_art_sup' => 'textarea',
    'si_cert_form_cap' => 'char',
    'nom_curs_form_capac' => 'textarea',
    'si_fue_cert' => 'char',
    'Num_contacts' => 'int',
    'int_nac_dep_art' => 'textarea',
    'corp_jud_leg' => 'textarea',
    'sec_jud_leg' => 'textarea',
    'dep_jud_leg' => 'textarea',

     'de_cont_dif_edu' => 'textarea',
    'cent_jud_leg' => 'textarea',
    'ong_depto' => 'textarea',
    'org_priv_depto' => 'textarea',
    'org_com_depto' => 'textarea',
    'otras_depto' => 'textarea',
    'si_fuer_edu_art_int' => 'char',
    'si_fuer_edu_gub_int' => 'char',
    'si_fuer_edu_art_no_int' => 'char',
    'si_fuer_no_gub' => 'char',
    'inst_nom_apoy_ext' => 'textarea',
    'num_anos_apoy' => 'int',
    'fin_tip_apoy' => 'textarea',
    'log_tip_apoy' => 'textarea',
    'tecn_tip_apoy' => 'textarea',
    'tec_peda_tip_apoy' => 'textarea',
    'ases_tip_apoy' => 'textarea',
    'acomp_tip_apoy' => 'textarea',
    'sin_tip_apoy' => 'textarea',
    'fin_nec_proy' => 'textarea',
    'log_nec_proy' => 'textarea',
    'tec_nec_proy' => 'textarea',
    'for_doc_nec_proy' => 'textarea',
    'tecn_pedag_nec_proy' => 'textarea',
    'ases_direc_doc_nec_proy' => 'textarea',
    'acomp_nec_proy' => 'textarea',
    'no_se_req_nec_proy' => 'textarea',
    'log_ano_ult' => 'int',
    'tecn_ano_ult' => 'int',
    'ases_ano_ult' => 'int',
    'fin_ano_ult' => 'int',
    'form_doc_ano_ult' => 'textarea',
    'tec_pedag_ano_ult' => 'textarea',
    'otro_ano_ult' => 'textarea',
    'no_requie_eficaz' => 'textarea',
    'Fue_oport' => 'char'
);


?>


